apiVersion: v1
kind: Service
metadata:
  name: serverscalingservice
  labels:
    app: serverscalingservice
spec:
  ports:
    - port: 8080
  selector:
    app: serverscalingservice
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: serverscalingservice
  labels:
    app: serverscalingservice
spec:
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: serverscalingservice
    spec:
      containers:
      - name: serverscalingservice
        image: exorath/serverscalingservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_URI
          value: "mongodb://IP:PORT"
        - name: DB_NAME
          value: "connectorservice"
        - name: CONNECTOR_SERVICE_ADDRESS
          value: "http://IP:PORT"
        - name: KUBERNETES_ADDRESS
          value: "http://IP:PORT"
        - name: KUBERNETES_CERTS_CA_DATA
          value: "INSERT_TOKEN"
